const questions = [
  {
    question_id: 12346,
    question: "What is the purpose of the 'package.json' file in a Node.js project?",
    option_1: "To define the project's dependencies",
    option_2: "To run the Node.js application",
    option_3: "To manage the project's version control",
    option_4: "All of the above",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12347,
    question: "Which of the following is not a built-in module in Node.js?",
    option_1: "HTTP",
    option_2: "FileSystem",
    option_3: "MongoDB",
    option_4: "Events",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12348,
    question: "What is the purpose of the 'require()' function in Node.js?",
    option_1: "To import a module into a Node.js application",
    option_2: "To export a module from a Node.js application",
    option_3: "To run a Node.js application",
    option_4: "To manage the project's dependencies",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12349,
    question: "What is the purpose of the 'express' module in Node.js?",
    option_1: "To handle HTTP requests and responses",
    option_2: "To manage the project's dependencies",
    option_3: "To run a Node.js application",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12350,
    question: "Which of the following is not a way to handle asynchronous operations in Node.js?",
    option_1: "Callbacks",
    option_2: "Promises",
    option_3: "Async/await",
    option_4: "Synchronous function calls",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12351,
    question: "What is the purpose of the 'npm' command in Node.js?",
    option_1: "To install packages and dependencies",
    option_2: "To run a Node.js application",
    option_3: "To manage the project's version control",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12352,
    question: "What is the purpose of the 'process' object in Node.js?",
    option_1: "To access the current process's environment variables",
    option_2: "To handle HTTP requests and responses",
    option_3: "To manage the project's dependencies",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12353,
    question: "What is the purpose of the 'module.exports' object in Node.js?",
    option_1: "To export a module from a Node.js application",
    option_2: "To import a module into a Node.js application",
    option_3: "To run a Node.js application",
    option_4: "To manage the project's dependencies",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12354,
    question: "What is the purpose of the 'middleware' concept in Node.js with the 'express' module?",
    option_1: "To handle HTTP requests and responses",
    option_2: "To manage the project's dependencies",
    option_3: "To run a Node.js application",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12355,
    question: "What is the purpose of the 'callback' function in Node.js?",
    option_1: "To handle asynchronous operations",
    option_2: "To manage the project's dependencies",
    option_3: "To run a Node.js application",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12356,
    question: "What is the purpose of the 'EventEmitter' module in Node.js?",
    option_1: "To handle asynchronous operations",
    option_2: "To manage the project's dependencies",
    option_3: "To handle events and emitters",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12357,
    question: "What is the purpose of the 'Buffer' class in Node.js?",
    option_1: "To handle binary data",
    option_2: "To manage the project's dependencies",
    option_3: "To handle events and emitters",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12358,
    question: "What is the purpose of the 'util' module in Node.js?",
    option_1: "To provide utility functions",
    option_2: "To manage the project's dependencies",
    option_3: "To handle events and emitters",
    option_4: "To handle file operations",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12359,
    question: "What is the purpose of the 'path' module in Node.js?",
    option_1: "To handle file paths",
    option_2: "To manage the project's dependencies",
    option_3: "To handle events and emitters",
    option_4: "To handle binary data",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  },
  {
    question_id: 12360,
    question: "What is the purpose of the 'fs' module in Node.js?",
    option_1: "To handle file operations",
    option_2: "To manage the project's dependencies",
    option_3: "To handle events and emitters",
    option_4: "To handle binary data",
    option_1_id: 4567,
    option_2_id: 8983,
    option_3_id: 9009,
    option_4_id: 8989
  }
];

const resultResponse =[
  {
    "question_id": 12346,
    "question": "What is the purpose of the 'package.json' file in a Node.js project?",
    "option_1": "To define the project's dependencies",
    "option_2": "To run the Node.js application",
    "option_3": "To manage the project's version control",
    "option_4": "All of the above",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 8989
  },
  {
    "question_id": 12347,
    "question": "Which of the following is not a built-in module in Node.js?",
    "option_1": "HTTP",
    "option_2": "FileSystem",
    "option_3": "MongoDB",
    "option_4": "Events",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 8983
  },
  {
    "question_id": 12348,
    "question": "What is the purpose of the 'require()' function in Node.js?",
    "option_1": "To import a module into a Node.js application",
    "option_2": "To export a module from a Node.js application",
    "option_3": "To run a Node.js application",
    "option_4": "To manage the project's dependencies",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12349,
    "question": "What is the purpose of the 'express' module in Node.js?",
    "option_1": "To handle HTTP requests and responses",
    "option_2": "To manage the project's dependencies",
    "option_3": "To run a Node.js application",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12350,
    "question": "Which of the following is not a way to handle asynchronous operations in Node.js?",
    "option_1": "Callbacks",
    "option_2": "Promises",
    "option_3": "Async/await",
    "option_4": "Synchronous function calls",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 8989
  },
  {
    "question_id": 12351,
    "question": "What is the purpose of the 'npm' command in Node.js?",
    "option_1": "To install packages and dependencies",
    "option_2": "To run a Node.js application",
    "option_3": "To manage the project's version control",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12352,
    "question": "What is the purpose of the 'process' object in Node.js?",
    "option_1": "To access the current process's environment variables",
    "option_2": "To handle HTTP requests and responses",
    "option_3": "To manage the project's dependencies",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12353,
    "question": "What is the purpose of the 'module.exports' object in Node.js?",
    "option_1": "To export a module from a Node.js application",
    "option_2": "To import a module into a Node.js application",
    "option_3": "To run a Node.js application",
    "option_4": "To manage the project's dependencies",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12354,
    "question": "What is the purpose of the 'middleware' concept in Node.js with the 'express' module?",
    "option_1": "To handle HTTP requests and responses",
    "option_2": "To manage the project's dependencies",
    "option_3": "To run a Node.js application",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12355,
    "question": "What is the purpose of the 'callback' function in Node.js?",
    "option_1": "To handle asynchronous operations",
    "option_2": "To manage the project's dependencies",
    "option_3": "To run a Node.js application",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12356,
    "question": "What is the purpose of the 'EventEmitter' module in Node.js?",
    "option_1": "To handle asynchronous operations",
    "option_2": "To manage the project's dependencies",
    "option_3": "To handle events and emitters",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 9009
  },
  {
    "question_id": 12357,
    "question": "What is the purpose of the 'Buffer' class in Node.js?",
    "option_1": "To handle binary data",
    "option_2": "To manage the project's dependencies",
    "option_3": "To handle events and emitters",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12358,
    "question": "What is the purpose of the 'util' module in Node.js?",
    "option_1": "To provide utility functions",
    "option_2": "To manage the project's dependencies",
    "option_3": "To handle events and emitters",
    "option_4": "To handle file operations",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12359,
    "question": "What is the purpose of the 'path' module in Node.js?",
    "option_1": "To handle file paths",
    "option_2": "To manage the project's dependencies",
    "option_3": "To handle events and emitters",
    "option_4": "To handle binary data",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  },
  {
    "question_id": 12360,
    "question": "What is the purpose of the 'fs' module in Node.js?",
    "option_1": "To handle file operations",
    "option_2": "To manage the project's dependencies",
    "option_3": "To handle events and emitters",
    "option_4": "To handle binary data",
    "option_1_id": 4567,
    "option_2_id": 8983,
    "option_3_id": 9009,
    "option_4_id": 8989,
    "correct_answer": 4567
  }
]

 

module.exports = { questions,   resultResponse };